CRITICAL - 2025-09-02 14:28:09 --> Error: Class "App\Controllers\PrestamosModel" not found
[Method: GET, Route: Prestamos]
in APPPATH\Controllers\Prestamos.php on line 8.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->Prestamos()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:28:43 --> Error: Class "App\Controllers\PrestamosModel" not found
[Method: GET, Route: Prestamos]
in APPPATH\Controllers\Prestamos.php on line 8.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->Prestamos()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:30:59 --> ErrorException: Undefined array key "codigo_prestamo"
[Method: GET, Route: Prestamos]
in APPPATH\Views\vista_prestamos.php on line 90.
 1 APPPATH\Views\vista_prestamos.php(90): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "codigo_prestamo"', 'C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Views\\vista_prestamos.php', 90)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Views\\vista_prestamos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('vista_prestamos', [], true)
 5 APPPATH\Controllers\Prestamos.php(10): view('vista_prestamos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->Prestamos()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:31:47 --> ParseError: Unclosed '{' on line 5
[Method: GET, Route: Prestamos]
in APPPATH\Controllers\Prestamos.php on line 54.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Controllers\\Prestamos.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Prestamos')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Prestamos')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\Prestamos', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:32:07 --> ErrorException: Undefined array key "codigo_prestamo"
[Method: GET, Route: Prestamos]
in APPPATH\Views\vista_prestamos.php on line 90.
 1 APPPATH\Views\vista_prestamos.php(90): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "codigo_prestamo"', 'C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Views\\vista_prestamos.php', 90)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Views\\vista_prestamos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('vista_prestamos', [], true)
 5 APPPATH\Controllers\Prestamos.php(10): view('vista_prestamos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->Prestamos()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:34:10 --> ErrorException: Undefined array key "codigo_prestamo"
[Method: GET, Route: Prestamos]
in APPPATH\Views\vista_prestamos.php on line 90.
 1 APPPATH\Views\vista_prestamos.php(90): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "codigo_prestamo"', 'C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Views\\vista_prestamos.php', 90)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025\\codeigniter4-Blackwave\\codeigniter4-framework-dbc07dc\\app\\Views\\vista_prestamos.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('vista_prestamos', [], true)
 5 APPPATH\Controllers\Prestamos.php(10): view('vista_prestamos', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->Prestamos()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-02 14:56:13 --> mysqli_sql_exception: Unknown column 'estado' in 'field list' in C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `prestam...', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestam...')
#2 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestam...')
#3 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestam...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\app\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', Array)
#8 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
#9 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
#10 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-02 14:56:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'estado' in 'field list'
[Method: POST, Route: editarPrestamo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:, `estado` = :estado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:56:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'estado' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:, `estado` = :estado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:56:13 --> [Caused by] mysqli_sql_exception: Unknown column 'estado' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:, `estado` = :estado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-02 14:56:26 --> mysqli_sql_exception: Unknown column 'estado' in 'field list' in C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `prestam...', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestam...')
#2 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestam...')
#3 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestam...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\app\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', Array)
#8 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
#9 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
#10 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-02 14:56:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'estado' in 'field list'
[Method: POST, Route: editarPrestamo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:, `estado` = :estado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:56:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'estado' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:, `estado` = :estado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 14:56:26 --> [Caused by] mysqli_sql_exception: Unknown column 'estado' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'2013101\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\', `estado` = NULL
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:, `estado` = :estado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-02 15:03:27 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2025_biblioteca`.`prestamos`, CONSTRAINT `prestamos_ibfk_2` FOREIGN KEY (`carne_alumno`) REFERENCES `estudiantes` (`carne_alumno`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `prestam...', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestam...')
#2 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestam...')
#3 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestam...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\BaseModel.php(1025): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(860): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\app\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', Array)
#8 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
#9 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
#10 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-02 15:03:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2025_biblioteca`.`prestamos`, CONSTRAINT `prestamos_ibfk_2` FOREIGN KEY (`carne_alumno`) REFERENCES `estudiantes` (`carne_alumno`) ON DELETE CASCADE ON UPDATE CASCADE)
[Method: POST, Route: editarPrestamo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 15:03:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`fs2025_biblioteca`.`prestamos`, CONSTRAINT `prestamos_ibfk_2` FOREIGN KEY (`carne_alumno`) REFERENCES `estudiantes` (`carne_alumno`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'20131010\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\'
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'20131010\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\'
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 15:03:27 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`fs2025_biblioteca`.`prestamos`, CONSTRAINT `prestamos_ibfk_2` FOREIGN KEY (`carne_alumno`) REFERENCES `estudiantes` (`carne_alumno`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'20131010\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\'
WHERE `prestamos`.`numero_prestamo` IN (\'2\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'20131010\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\'
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `prestamos` SET `numero_prestamo` = \'2\', `codigo_libro` = \'100422\', `carne_alumno` = \'20131010\', `fecha_prestamo` = \'2019-03-16\', `fecha_devolucion` = \'2019-03-19\', `codigo_empleado` = \'1001\'
WHERE `prestamos`.`numero_prestamo` IN (\'2\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `prestamos` SET `numero_prestamo` = :numero_prestamo:, `codigo_libro` = :codigo_libro:, `carne_alumno` = :carne_alumno:, `fecha_prestamo` = :fecha_prestamo:, `fecha_devolucion` = :fecha_devolucion:, `codigo_empleado` = :codigo_empleado:
WHERE `prestamos`.`numero_prestamo` IN :prestamos.numero_prestamo:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1025): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(860): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Prestamos.php(37): CodeIgniter\Model->update('2', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->editarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-02 15:17:13 --> mysqli_sql_exception: Column 'numero_prestamo' cannot be null in C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\app\Controllers\Prestamos.php(52): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
#9 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
#10 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-02 15:17:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'numero_prestamo' cannot be null
[Method: POST, Route: agregarPrestamo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (:numero_prestamo:, :codigo_libro:, :carne_alumno:, :fecha_prestamo:, :fecha_devolucion:, :codigo_empleado:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Prestamos.php(52): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 15:17:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'numero_prestamo' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (:numero_prestamo:, :codigo_libro:, :carne_alumno:, :fecha_prestamo:, :fecha_devolucion:, :codigo_empleado:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Prestamos.php(52): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 15:17:13 --> [Caused by] mysqli_sql_exception: Column 'numero_prestamo' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (:numero_prestamo:, :codigo_libro:, :carne_alumno:, :fecha_prestamo:, :fecha_devolucion:, :codigo_empleado:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Prestamos.php(52): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-02 15:17:34 --> mysqli_sql_exception: Column 'numero_prestamo' cannot be null in C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\app\Controllers\Prestamos.php(52): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
#9 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
#10 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025\codeigniter4-Blackwave\codeigniter4-framework-dbc07dc\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-02 15:17:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'numero_prestamo' cannot be null
[Method: POST, Route: agregarPrestamo]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (:numero_prestamo:, :codigo_libro:, :carne_alumno:, :fecha_prestamo:, :fecha_devolucion:, :codigo_empleado:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Prestamos.php(52): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 15:17:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'numero_prestamo' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (:numero_prestamo:, :codigo_libro:, :carne_alumno:, :fecha_prestamo:, :fecha_devolucion:, :codigo_empleado:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Prestamos.php(52): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-02 15:17:34 --> [Caused by] mysqli_sql_exception: Column 'numero_prestamo' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (NULL, NULL, \'2013002\', \'2025-09-04\', \'2025-09-25\', \'1001\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`numero_prestamo`, `codigo_libro`, `carne_alumno`, `fecha_prestamo`, `fecha_devolucion`, `codigo_empleado`) VALUES (:numero_prestamo:, :codigo_libro:, :carne_alumno:, :fecha_prestamo:, :fecha_devolucion:, :codigo_empleado:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Prestamos.php(52): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Prestamos->agregarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Prestamos))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
